### ISSUE TITLE
couldn't decode - got incompatible marshal file format (can't be read)

### ISSUE THREAD

**Issue by niwo** [markevans/dragonfly#190]
I see this error when trying to serve a webm video from rails 3.2.3 using Dragonfly 0.9.12 (Rack::Cache 1.2).
Possibly the problems comes from Rack::Cache (the video itself is not stored using dragonfly):

```
cache: [GET /media/video.webm] miss
couldn't decode video - got incompatible marshal file format (can't be read)
    format version 4.8 required; 110.184 given
```

The mimetype vor webm is registered using an initializer:

``` ruby
Rack::Mime::MIME_TYPES.merge!({
  ".webm"    => "video/webm"
}
```

Also registering the mime type under Dragonfly doesn't help:

``` ruby
Dragonfly[:app_name].register_mime_type(:webm, 'video/webm')
```

After deactivating rack-cache/dragonfly I can serve the video without any problem.

**Comment by pjmorse** [comment]
I'm seeing this issue upgrading from 0.9.12 to 1.0.12. It's a Rails 3.2 app, if that matters. The error message crops up on *all* requests - in the branch where I'm doing the upgrade, it has essentially hamstrung the app. I get this:

    DRAGONFLY: couldn't marshal decode string - got incompatible marshal file format (can't be read)
	format version 4.8 required; 105.217 given

Dragonfly is configured to use the S3 data store, so there's no tmp/dragonfly folder to clear. Because it shows up on *all* paths, it's not clear how to resolve the conflict - maybe I broke the configuration somehow?
