### ISSUE TITLE
Ruby cannot allocate memory

### ISSUE THREAD

**Issue by dlibanori** [markevans/dragonfly#308]
Ruby cannot spawn `identify` when your ruby process takes more memory than free memory.

Actually, I think it is ruby's fault, but I just can't find any report about this. You may take a look at [this gist](https://gist.github.com/dlibanori/8479129). This guy produces [funny results](https://gist.github.com/dlibanori/8479247). I have tested it on Ruby 1.9.3, 2.0.0 and 2.1.0 with same output. If you remove _backtick_ call, everything works fine.

Anyway, I think _Dragonfly_ should avoid use of _backtick_ and `%x`.

**Comment by rdetert** [comment]
@dlibanori Can you provide any more info on using the `system` strategy? I'm running into a similar issue on Heroku. Every once in a while one bad image will get uploaded that the system commands can't handle and it will crash my app.

I get this: `Error R15 (Memory quota vastly exceeded)`

**Comment by dlibanori** [comment]
@rdetert I don't know if this issue is still valid cause I was working with ruby <= 2.10. But I Just replaced backticks by `system`. I guess, today's ruby is more friendly if _copy on write_ strategy

**Comment by rdetert** [comment]
@dlibanori I found the problem. The JPEGs were not generated properly and even though they were only 3MB, the apps reading them thought they were 500MB. Running `convert` from the command line used up about 1GB of memory on my Mac and on Heroku. It would be nice to have some sort of sanity check or way to fail gracefully, otherwise one bad image could bring down the entire website.
