### ISSUE TITLE
Serializing with to_yaml

### ISSUE THREAD

**Issue by wvteijlingen** [markevans/dragonfly#461]
I found that adding an attachment using `dragonfly_accessor` breaks `to_yaml` on that object. It throws a `TypeError - can't dump anonymous module`. Is this just a result of the Dragonfly architecture, and if so, would there be any way to get around this?

Example:

```ruby
class Person
  extend Dragonfly::Model
  attr_accessor :attachment_uid
  dragonfly_accessor :attachment
end

person = Person.new
person.attachment = Dragonfly.app.fetch_file("file.png")
yams = person.to_yaml
```

**Comment by markevans** [comment]
Hi - to_yaml seems to just dump any instance vars, e.g.

    obj = Object.new
    obj.instance_eval{ @a = Module.new }
    obj.to_yaml

gives the same error, as Module.new has no name (as opposed to `Module A; end`)

So yes, this is a result of Dragonfly using anonymous modules like the above somewhere (that's definitely done once or twice in the code)

I'm not sure what you're using to_yaml for but maybe you could specify which attributes to load/dump rather than using to_yaml to blindly dump all instance vars?

**Comment by wvteijlingen** [comment]
Yeah i figured it was something like that. But good to know for sure :). I'll solve it by only dumping and loading attributes that I need. Thanks!
